CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS hostel_db;
CREATE DATABASE IF NOT EXISTS guest_db;
CREATE DATABASE IF NOT EXISTS billing_db;
