-- PG Management - PostgreSQL schema

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname             VARCHAR(255) NOT NULL,
    lname             VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    profilepictureurl VARCHAR(255),
    role              VARCHAR(255) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_password UNIQUE (password)
);

CREATE TABLE hostel (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    owner_id      BIGINT NOT NULL,
    name          VARCHAR(255) NOT NULL,
    street        VARCHAR(255),
    city          VARCHAR(255),
    state         VARCHAR(255),
    pin_code      INTEGER,
    contact_phone VARCHAR(255),
    contact_email VARCHAR(255)
);

CREATE TABLE floor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id    BIGINT NOT NULL,
    floor_number INTEGER NOT NULL,
    name         VARCHAR(255)
);

CREATE TABLE room (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id   BIGINT NOT NULL,
    floor_id    BIGINT,
    room_number VARCHAR(255) NOT NULL,
    capacity    INTEGER NOT NULL DEFAULT 1,
    monthly_rent DOUBLE PRECISION NOT NULL,
    status      VARCHAR(255) NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE guest (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id         BIGINT NOT NULL,
    tenant_id         BIGINT NOT NULL,
    name              VARCHAR(255) NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    email             VARCHAR(255),
    id_proof          VARCHAR(255),
    emergency_contact VARCHAR(255),
    address           VARCHAR(255),
    created_at        TIMESTAMP(6) NOT NULL
);

CREATE TABLE room_assignment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id       BIGINT NOT NULL,
    room_id        BIGINT NOT NULL,
    hostel_id      BIGINT NOT NULL,
    check_in_date  DATE NOT NULL,
    check_out_date DATE,
    monthly_rent   DOUBLE PRECISION NOT NULL,
    active         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    hostel_id       BIGINT NOT NULL,
    guest_id        BIGINT NOT NULL,
    assignment_id   BIGINT NOT NULL,
    month           INTEGER NOT NULL,
    year            INTEGER NOT NULL,
    total_amount    DOUBLE PRECISION NOT NULL,
    late_fee        DOUBLE PRECISION,
    partial_payment DOUBLE PRECISION,
    due_amount      DOUBLE PRECISION,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    due_date        DATE,
    created_at      TIMESTAMP(6)
);

CREATE TABLE payment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     BIGINT NOT NULL,
    amount         DOUBLE PRECISION NOT NULL,
    method         VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255),
    notes          VARCHAR(255),
    payment_date   TIMESTAMP(6) NOT NULL
);

ALTER TABLE hostel
    ADD CONSTRAINT fk_hostel_owner
        FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE floor
    ADD CONSTRAINT fk_floor_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE room
    ADD CONSTRAINT fk_room_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE room
    ADD CONSTRAINT fk_room_floor
        FOREIGN KEY (floor_id) REFERENCES floor (id);

ALTER TABLE guest
    ADD CONSTRAINT fk_guest_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE room_assignment
    ADD CONSTRAINT fk_room_assignment_guest
        FOREIGN KEY (guest_id) REFERENCES guest (id);

ALTER TABLE room_assignment
    ADD CONSTRAINT fk_room_assignment_room
        FOREIGN KEY (room_id) REFERENCES room (id);

ALTER TABLE room_assignment
    ADD CONSTRAINT fk_room_assignment_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice_guest
        FOREIGN KEY (guest_id) REFERENCES guest (id);

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice_assignment
        FOREIGN KEY (assignment_id) REFERENCES room_assignment (id);

ALTER TABLE payment
    ADD CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoice (id);

CREATE INDEX idx_users_tenant_id ON users (tenant_id);
CREATE INDEX idx_hostel_tenant_id ON hostel (tenant_id);
CREATE INDEX idx_hostel_owner_id ON hostel (owner_id);
CREATE INDEX idx_floor_hostel_id ON floor (hostel_id);
CREATE INDEX idx_room_hostel_id ON room (hostel_id);
CREATE INDEX idx_room_floor_id ON room (floor_id);
CREATE INDEX idx_guest_hostel_id ON guest (hostel_id);
CREATE INDEX idx_guest_tenant_id ON guest (tenant_id);
CREATE INDEX idx_room_assignment_guest_id ON room_assignment (guest_id);
CREATE INDEX idx_room_assignment_room_id ON room_assignment (room_id);
CREATE INDEX idx_room_assignment_hostel_id ON room_assignment (hostel_id);
CREATE INDEX idx_invoice_tenant_id ON invoice (tenant_id);
CREATE INDEX idx_invoice_hostel_id ON invoice (hostel_id);
CREATE INDEX idx_invoice_guest_id ON invoice (guest_id);
CREATE INDEX idx_invoice_assignment_id ON invoice (assignment_id);
CREATE INDEX idx_payment_invoice_id ON payment (invoice_id);
